---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run all tests

    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
    env:
      # Based on the Maven CI/CD template from GitLab:
      # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml
      # It is recommended to use these variables to reduce noise in the logs
      MAVEN_OPTS: >
        -Dhttps.protocols=TLSv1.2
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
        -Dorg.slf4j.simpleLogger.showDateTime=true
        -Djava.awt.headless=true
      MAVEN_CLI_OPTS: >
        --batch-mode
        --errors
        --fail-at-end
        --show-version
        -DinstallAtEnd=true
        -DdeployAtEnd=true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Run unit tests
        run: mvn $MAVEN_CLI_OPTS test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
                git config --global user.name 'YOUR NAME HERE'
                git config --global user.email 'YOUR-GITHUB-USERID@users.noreply.github.com'
                git add -A
                git commit -m "Autogenerated JaCoCo coverage badge"
                git push
          fi
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
  deploy:
    needs: test
    runs-on: ubuntu-22.04
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Install dpl
        run: gem install dpl
      - name: Deploy to Heroku
        run: dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        with:
          initial_status: success
          token: ${{ github.token }}
          target_url: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com
          environment: production
